# [WELCOME]
# This is the repository conf file for all repos except system which also has one more file in /etc/. 
# For system (Official distro packages) all important keys are stored in /etc/captain-slack/system-repo.env
# To enable it you must edit it "SYSTEM_REPO=ON" and here ONLY change 'priority: x' to something higher than 0 (zero)

# [NOTE]
# Every repo here has by default "priority: 0" 
# that means all repos are disabled. Higher priority means higher priority against other repos also. (similar to slackpkg+)

# NOTE, that since by default ALL repos has "priority: 0", this way you install Captain-Slack as non package manager 
# and use it only for it's tool collection.

# [SETTINGS] 
# "type: web" {means repo url is http(s)--> so cptn use wget for download files
# "type: git" {means repo url is git--> cptn use git to sync
# "type2: bin" {means repo provide binaries *.t?z}
# "type2: build" {means repo provide SlackBuilds}
#
# pkg_structure: {notag,normal,build_version} 
# 1. "notag" means that package dont use _tag in its name (official packages) foo-1.2.0-x86_64-1.txz
# 2. "normal" means _tag like _SBo _gfs etc...................................foo-1.2.0-x86_64-1_SBo.txz
# 3. "build_version" means how alienBOB or conraid building their packages....foo-1.2.0-x86_64-1alien.txz
#   - They do use tag but not _ (underscore).

resources:
  repositories:
    - repository: system
      type: web
      type2: bin
      url: "http://example.com/system/"
      branch: []
      description: "Official Slackware Repository"
      maintainers:
        - name: Patrick Volkerding
          email: volkerdi@slackware.com
      arch: 
        - x86 
        - x86_64
      pkg_structure: notag
      comments: "System repo is OFF by default. Edit system.env to enable."
      priority: 0

    - repository: system
      type: web
      type2: bin
      url: "http://example.com/aarch64/"
      branch: []
      description: "Official aarch64 Repository"
      maintainers:
        - name: Stuart Winter
          email: mozes@slackware.com
      arch: 
        - aarch64
      pkg_structure: notag
      comments: "System repo for aarch64 is OFF by default. Enable it in system.env."
      priority: 0

    - repository: SBo
      VERSION_CODENAME: stable
      type: git
      type2: build
      url: "https://github.com/SlackBuildsOrg/slackbuilds.git"
      branch: master
      description: "SlackBuilds.org"
      maintainers:
        - name: community
          email: mailman@slackbuilds.org
      comments: ""
      priority: 0  

    - repository: ponce
      VERSION_CODENAME: current
      type: git
      type2: build
      url: "https://github.com/Ponce/slackbuilds.git"
      branch: current
      description: "Unofficial fork of SlackBuilds.org for Slackware-current"
      maintainers:
        - name: Matteo Bernardini
          email: matteo.bernardini@gmail.com
        - name: community
          email: mailman@slackbuilds.org
      comments: ""
      priority: 0

    - repository: gnome
      VERSION_CODENAME: current
      type: web
      type2: bin
      url: "https://reddoglinux.ddns.net/linux/gnome/"
      branch: "46.x/"
      description: "Repository for Gnome DE"
      maintainers:
        - name: Nathaniel Russell
          email: naterussell83@gmail.com
      arch:
        - x86_64
      pkg_structure: normal
      comments: ""
      priority: 0  

    - repository: cosmic
      VERSION_CODENAME: current
      type: web
      type2: bin
      url: "https://reddoglinux.ddns.net/linux/"
      branch: "cosmic/"
      description: "Repository for Cosmic DE"
      maintainers:
        - name: Nathaniel Russell
          email: naterussell83@gmail.com
      arch:
        - x86_64
      pkg_structure: normal
      comments: ""
      priority: 0  

    - repository: kde6
      VERSION_CODENAME: current
      type: web
      type2: bin
      url: "https://slackware.lngn.net/pub/"
      branches:
        - name: slackware64-current
          arch: x86_64
          path: "kde6/"
        - name: slackwareaarch64-current
          arch: aarch64
          path: "kde6/"
      description: "Repository for Plasma 6 DE"
      maintainers:
        - name: Jay Lanagan
          email: j@lngn.net
      pkg_structure: normal
      comments: ""
      priority: 0  

    - repository: nwg-shell
      VERSION_CODENAME: current
      type: web
      type2: bin
      url: "https://slackware.lngn.net/pub/"
      branches:
        - name: slackware64-current
          arch: x86_64
          path: "nwg-shell/"
        - name: slackwareaarch64-current
          arch: aarch64
          path: "nwg-shell/"
      description: "Repository for nwg-shell (Hyprland, Sway & misc)"
      maintainers:
        - name: Jay Lanagan
          email: j@lngn.net
      pkg_structure: normal
      comments: ""
      priority: 0  

    - repository: conraid
      VERSION_CODENAME: current
      type: web
      type2: bin
      url: "https://slackers.it/repository/slackware64-current/"
      branches:
        - name: slackware64-current
          arch: x86_64
          path: ""
      description: "Slackware Current Repository by Conraid"
      maintainers:
        - name: Corrado Franco
          email: slackers.it@gmail.com
      pkg_structure: build_version
      comments: ""
      priority: 0  

    - repository: multilib
      type: web
      type2: bin
      url: "https://slackware.nl/people/alien/multilib/"
      branches:
        - name: 15.0
          arch: x86_64
          path: ""
        - name: current
          arch: x86_64
          path: ""
      description: "Slackware for x86_64 - multilib packages"
      maintainers:
        - name: Eric Hameleers
          email: alien@slackware.com
      pkg_structure: build_version
      comments: ""
      priority: 0  

    - repository: restricted
      type: web
      type2: bin
      url: "https://slackware.nl/people/alien/restricted_sbrepos/"
      branches:
        - name: 15.0
          arch: x86
          path: "x86/"
        - name: 15.0
          arch: x86_64
          path: "x86_64/"
        - name: current
          arch: x86
          path: "x86/"
        - name: current
          arch: x86_64
          path: "x86_64/"
      description: "Slackware restricted_sbrepos"
      maintainers:
        - name: Eric Hameleers
          email: alien@slackware.com
      pkg_structure: build_version
      comments: ""
      priority: 0  

    - repository: sbrepos
      type: web
      type2: bin
      url: "https://slackware.nl/people/alien/sbrepos/"
      branches:
        - name: 15.0
          arch: x86
          path: "x86/"
        - name: 15.0
          arch: x86_64
          path: "x86_64/"
        - name: current
          arch: x86
          path: "x86/"
        - name: current
          arch: x86_64
          path: "x86_64/"
      description: "Slackware alien sbrepos"
      maintainers:
        - name: Eric Hameleers
          email: alien@slackware.com
      pkg_structure: build_version
      comments: ""
      priority: 0
